// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StreamChatInator.Database;

#nullable disable

namespace StreamChatInator.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260810235632_AddBadgesToChatEvents")]
    partial class AddBadgesToChatEvents
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("StreamChatInator.Database.Models.ChatEvent", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("ChatEventType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Seen")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ChatEvents", (string)null);
                });

            modelBuilder.Entity("StreamChatInator.Database.Models.ChatEventAnnouncement", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChatUserNoticeBaseId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MsgParamColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ChatEventAnnouncements", (string)null);
                });

            modelBuilder.Entity("StreamChatInator.Database.Models.ChatEventAnonGiftPaidUpgrade", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChatUserNoticeBaseId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<int>("MsgParamPromoGiftTotal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MsgParamPromoName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ChatEventAnonGiftPaidUpgrades", (string)null);
                });

            modelBuilder.Entity("StreamChatInator.Database.Models.ChatEventBitsBadgeTier", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChatUserNoticeBaseId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<int>("MsgParamThreshold")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ChatEventBitsBadgeTiers", (string)null);
                });

            modelBuilder.Entity("StreamChatInator.Database.Models.ChatEventChatMessage", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Badges")
                        .HasColumnType("TEXT");

                    b.Property<int>("Bits")
                        .HasColumnType("INTEGER");

                    b.Property<double>("BitsInDollars")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomRewardId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Emotes")
                        .HasColumnType("TEXT");

                    b.Property<string>("HexColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBroadcaster")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFirstMessage")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHighlighted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsMe")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSkippingSubMode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Noisy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReplyParentMessageTwitchMessageId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SubscribedMonthCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TmiSent")
                        .HasColumnType("TEXT");

                    b.Property<string>("TwitchMessageId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserFlags")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte>("UserType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ChatEventChatMessages", (string)null);
                });

            modelBuilder.Entity("StreamChatInator.Database.Models.ChatEventCommunityPayForward", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChatUserNoticeBaseId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<bool>("MsgParamPriorGifterAnonymous")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MsgParamPriorGifterDisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MsgParamPriorGifterId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MsgParamPriorGifterUserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ChatEventCommunityPayForwards", (string)null);
                });

            modelBuilder.Entity("StreamChatInator.Database.Models.ChatEventCommunitySubscription", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChatUserNoticeBaseId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAnonymous")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MsgParamGiftTheme")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MsgParamMassGiftCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MsgParamOriginId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MsgParamSenderCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MsgParamSubPlan")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ChatEventCommunitySubscriptions", (string)null);
                });

            modelBuilder.Entity("StreamChatInator.Database.Models.ChatEventContinuedGiftedSubscription", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChatUserNoticeBaseId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<int>("MsgParamPromoGiftTotal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MsgParamPromoName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MsgParamSenderName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MsgParamSenderUsername")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ChatEventContinuedGiftedSubscriptions", (string)null);
                });

            modelBuilder.Entity("StreamChatInator.Database.Models.ChatEventFilter", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CodeJs")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("EventFilters", (string)null);
                });

            modelBuilder.Entity("StreamChatInator.Database.Models.ChatEventGiftedSubscription", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChatUserNoticeBaseId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAnonymous")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MsgParamMonths")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MsgParamMultiMonthGiftDuration")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MsgParamOriginId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MsgParamRecipientDisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MsgParamRecipientId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MsgParamRecipientUserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MsgParamSenderCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MsgParamSubPlan")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MsgParamSubPlanName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ChatEventGiftedSubscriptions", (string)null);
                });

            modelBuilder.Entity("StreamChatInator.Database.Models.ChatEventMessageCleared", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetTwitchMessageId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TmiSent")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ChatEventMessageCleareds", (string)null);
                });

            modelBuilder.Entity("StreamChatInator.Database.Models.ChatEventNewSubscriber", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChatUserNoticeBaseId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<int>("MsgParamCumulativeMonths")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("MsgParamShouldShareStreak")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MsgParamStreakMonths")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MsgParamSubPlan")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MsgParamSubPlanName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResubMessage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ChatEventNewSubscribers", (string)null);
                });

            modelBuilder.Entity("StreamChatInator.Database.Models.ChatEventPrimePaidSubscriber", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChatUserNoticeBaseId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<int>("MsgParamSubPlan")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResubMessage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ChatEventPrimePaidSubscribers", (string)null);
                });

            modelBuilder.Entity("StreamChatInator.Database.Models.ChatEventReSubscriber", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChatUserNoticeBaseId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<int>("MsgParamCumulativeMonths")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("MsgParamShouldShareStreak")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MsgParamStreakMonths")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MsgParamSubPlan")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MsgParamSubPlanName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResubMessage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ChatEventReSubscribers", (string)null);
                });

            modelBuilder.Entity("StreamChatInator.Database.Models.ChatEventRitual", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChatUserNoticeBaseId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MsgParamRitualName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ChatEventRituals", (string)null);
                });

            modelBuilder.Entity("StreamChatInator.Database.Models.ChatEventStandardPayForward", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChatUserNoticeBaseId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<bool>("MsgParamPriorGifterAnonymous")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MsgParamPriorGifterDisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MsgParamPriorGifterId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MsgParamPriorGifterUserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MsgParamRecipientDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("MsgParamRecipientId")
                        .HasColumnType("TEXT");

                    b.Property<string>("MsgParamRecipientUserName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ChatEventStandardPayForwards", (string)null);
                });

            modelBuilder.Entity("StreamChatInator.Database.Models.ChatEventUserBanned", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoomId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ChatEventUserBanneds", (string)null);
                });

            modelBuilder.Entity("StreamChatInator.Database.Models.ChatEventUserJoined", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ChatEventUserJoineds", (string)null);
                });

            modelBuilder.Entity("StreamChatInator.Database.Models.ChatEventUserLeft", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ChatEventUserLefts", (string)null);
                });

            modelBuilder.Entity("StreamChatInator.Database.Models.ChatEventUserTimedout", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("TimeoutDuration")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ChatEventUserTimedouts", (string)null);
                });

            modelBuilder.Entity("StreamChatInator.Database.Models.ChatUserNoticeBase", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Badges")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Emotes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HexColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MsgId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RoomId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SystemMsg")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TmiSent")
                        .HasColumnType("TEXT");

                    b.Property<string>("TwitchMessageId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserFlags")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte>("UserType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ChatUserNoticeBases", (string)null);
                });

            modelBuilder.Entity("StreamChatInator.Database.Models.SettingValue", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SettingValues", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
