// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StreamChatInator.Database;

#nullable disable

namespace StreamChatInator.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("StreamChatInator.Database.Models.ChatEvent", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("ChatEventType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ChatEvents", (string)null);
                });

            modelBuilder.Entity("StreamChatInator.Database.Models.ChatEventMessage", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("Bits")
                        .HasColumnType("INTEGER");

                    b.Property<double>("BitsInDollars")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomRewardId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmoteReplacedMessage")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBroadcaster")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFirstMessage")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHighlighted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsMe")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSkippingSubMode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Noisy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReplyParentMessageTwitchMessageId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SubscribedMonthCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("TmiSent")
                        .HasColumnType("TEXT");

                    b.Property<string>("TwitchMessageId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ChatEventsMessages", (string)null);
                });

            modelBuilder.Entity("StreamChatInator.Database.Models.SettingValue", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SettingValues", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
