using TwitchLib.Client.Enums;
using TwitchLib.Client.Models;

namespace StreamChatInator.Database.Models
{
    public class ChatEventChatMessage : Model
    {
        /// <summary>
        /// If viewer sent bits in their message, total amount will be here. 
        /// </summary>
        public required int Bits { get; set; }

        /// <summary>
        /// Number of USD (United States Dollars) spent on bits.
        /// </summary>
        public required double BitsInDollars { get; set; }

        /// <summary>
        /// the emote set string of this message
        /// </summary>
        public required string? Emotes { get; set; }

        /// <summary>
        /// If a custom reward is present with the message, the ID will be set (null by default)
        /// </summary>
        public required string? CustomRewardId { get; set; }

        /// <summary>
        /// Unique message identifier assigned by Twitch
        /// </summary>
        public required string TwitchMessageId { get; set; }

        /// <summary>
        /// Is Chat message from broadcaster identifier flag
        /// </summary>
        public required bool IsBroadcaster { get; set; }

        /// <summary>
        /// Chat message is the first message, ever, from this user in this chat
        /// </summary>
        public required bool IsFirstMessage { get; set; }

        /// <summary>
        /// Chat message is highlighted in chat via channel points
        /// </summary>
        public required bool IsHighlighted { get; set; }

        /// <summary>
        /// Chat message /me identifier flag.
        /// </summary>
        public required bool IsMe { get; set; }

        /// <summary>
        /// Message used channel points to skip sub mode
        /// </summary>
        public required bool IsSkippingSubMode { get; set; }

        /// <summary>
        /// Twitch chat message contents.
        /// </summary>
        public required string Message { get; set; }

        /// <summary>
        /// Experimental property noisy determination by Twitch.
        /// </summary>
        public required Noisy Noisy { get; set; }

        /// <summary>
        /// Number of months a person has been subbed.
        /// </summary>
        public required int SubscribedMonthCount { get; set; }

        /// <summary>
        /// Sent timestamp generated by TMI
        /// </summary>
        public required DateTime TmiSent { get; set; }

        /// <summary>
        /// if this is a reply, this will hold the message id of the replied to message
        /// </summary>
        public required string? ReplyParentMessageTwitchMessageId { get; set; }

        public bool IsReply { get { return ReplyParentMessageTwitchMessageId != null; } }

        /// <summary>
        /// Username of sender of chat message.
        /// </summary>
        public required string DisplayName { get; set; }

        /// <summary>
        /// Twitch-unique integer assigned on per account basis.
        /// </summary>        
        public required string UserId { get; set; }

        /// <summary>
        /// Username of sender of chat message.
        /// </summary>
        public required string Username { get; set; }

        /// <summary>
        /// Property representing HEX color as a System.Drawing.Color object.
        /// </summary>
        public required string HexColor { get; set; }

        /// <summary>
        /// The user's chat badges as Twitch sent them in the message's badge tag,
        /// serialized as a JSON array of {"set": "...", "version": "..."} entries.
        /// This is the ground truth for which badges to render on the client; the
        /// user flags/type below are only a fallback for badges missing from it
        /// (e.g. subscriber tier, VIP, founder).
        /// </summary>
        public required string? Badges { get; set; }

        /// <summary>
        /// Flags about the user, like moderator|turbo|vip etc
        /// </summary>
        public required UserDetails UserFlags { get; set; }

        /// <summary>
        /// UserFlags broken out into individual flag names, for easy client-side filtering
        /// (e.g. userFlagNames.includes("Moderator")) instead of dealing with the raw bitmask.
        /// </summary>
        public string[] UserFlagsNames => Util.FlagEnumNames(UserFlags);


        /// <summary>
        /// User type can be viewer, moderator, global mod, admin, or staff
        /// </summary>
        public required UserType UserType { get; set; }

        public string UserTypeName { get { return UserType.ToString(); } }

        public static ChatEventChatMessage FromChatMessage(ChatMessage msg)
        {
            var chatMessage = new ChatEventChatMessage()
            {
                Id = GetNewId<ChatEventChatMessage>(),
                Bits = msg.Bits,
                Emotes = msg.EmoteSet.RawEmoteSetString,
                BitsInDollars = msg.BitsInDollars,
                CustomRewardId = msg.CustomRewardId,
                Message = msg.Message,
                IsBroadcaster = msg.IsBroadcaster,
                IsFirstMessage = msg.IsFirstMessage,
                IsHighlighted = msg.IsHighlighted,
                IsMe = msg.IsMe,
                IsSkippingSubMode = msg.IsSkippingSubMode,
                Noisy = msg.Noisy,
                ReplyParentMessageTwitchMessageId = msg.ChatReply?.ParentMsgId,
                SubscribedMonthCount = msg.SubscribedMonthCount,
                TmiSent = msg.TmiSent.UtcDateTime,
                TwitchMessageId = msg.Id,
                DisplayName = msg.DisplayName,
                UserId = msg.UserId,
                Username = msg.Username,
                UserFlags = Util.GetPrivateFieldNotNull<UserDetails>(msg.UserDetail, "_flags"),
                UserType = msg.UserType,
                HexColor = msg.HexColor,
                Badges = Util.SerializeBadges(msg.Badges),
            };

            return chatMessage;
        }
    }
}
