using TwitchLib.Client.Enums;
using TwitchLib.Client.Models;

namespace StreamChatInator.Database.Models
{
    public class ChatEventMessage : Model
    {
        /// <summary>
        /// If viewer sent bits in their message, total amount will be here. 
        /// </summary>
        public required int Bits { get; set; }

        /// <summary>
        /// Number of USD (United States Dollars) spent on bits.
        /// </summary>
        public required double BitsInDollars { get; set; }

        /// <summary>
        /// If a custom reward is present with the message, the ID will be set (null by default)
        /// </summary>
        public required string? CustomRewardId { get; set; }

        /// <summary>
        /// Text after emotes have been handled (if desired). Will be null if replaceEmotes is false.
        /// </summary>
        public required string? EmoteReplacedMessage { get; set; }

        public bool HasEmotes { get { return EmoteReplacedMessage != null; } }

        /// <summary>
        /// Unique message identifier assigned by Twitch
        /// </summary>
        public required string TwitchMessageId { get; set; }

        /// <summary>
        /// Is Chat message from broadcaster identifier flag
        /// </summary>
        public required bool IsBroadcaster { get; set; }

        /// <summary>
        /// Chat message is the first message, ever, from this user in this chat
        /// </summary>
        public required bool IsFirstMessage { get; set; }

        /// <summary>
        /// Chat message is highlighted in chat via channel points
        /// </summary>
        public required bool IsHighlighted { get; set; }

        /// <summary>
        /// Chat message /me identifier flag.
        /// </summary>
        public required bool IsMe { get; set; }

        /// <summary>
        /// Message used channel points to skip sub mode
        /// </summary>
        public required bool IsSkippingSubMode { get; set; }

        /// <summary>
        /// Twitch chat message contents.
        /// </summary>
        public required string Message { get; set; }

        /// <summary>
        /// Experimental property noisy determination by Twitch.
        /// </summary>
        public required Noisy Noisy { get; set; }

        /// <summary>
        /// Number of months a person has been subbed.
        /// </summary>
        public required int SubscribedMonthCount { get; set; }

        /// <summary>
        /// Sent timestamp generated by TMI
        /// </summary>
        public required DateTimeOffset TmiSent { get; set; }

        /// <summary>
        /// if this is a reply, this will hold the message id of the replied to message
        /// </summary>
        public required string? ReplyParentMessageTwitchMessageId { get; set; }

        public bool IsReply { get { return ReplyParentMessageTwitchMessageId != null; } }
    }
}
